/**
 * Licence tool for the vendor (you). Keep the private key OFF the shop's devices and out of git.
 *
 *   npm run license -- keygen                       create the signing key (once) and update src/license/publicKey.ts
 *   npm run license -- issue --device ABCD-EFGH-JKLM --name "Mama Nkechi Stores" [--days 365 | --expires 2027-12-31]
 *   npm run license -- verify --device ABCD-EFGH-JKLM --code <activation code>
 *
 * The private key lives in mobile/.license/private-key.json (git-ignored). Back it up: without
 * it you cannot issue codes for apps already built with its public key.
 */
import { randomBytes, randomUUID } from "node:crypto";
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { issueLicense, normalizeDeviceCode, publicKeyFor, verifyLicense, type LicensePayload } from "../src/license/license";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const keyDir = join(root, ".license");
const keyFile = join(keyDir, "private-key.json");
const issuedLog = join(keyDir, "issued.csv");
const publicKeyModule = join(root, "src", "license", "publicKey.ts");

function option(name: string) {
  const index = process.argv.indexOf(`--${name}`);
  return index === -1 ? undefined : process.argv[index + 1];
}

function loadSecret() {
  if (!existsSync(keyFile)) throw new Error(`No signing key at ${keyFile}. Run: npm run license -- keygen`);
  return (JSON.parse(readFileSync(keyFile, "utf8")) as { secretKey: string }).secretKey;
}

function writePublicKey(publicKeyHex: string) {
  writeFileSync(
    publicKeyModule,
    `/** Public half of the vendor's licence signing key (generated by \`npm run license -- keygen\`). */\nexport const LICENSE_PUBLIC_KEY = "${publicKeyHex}";\n`
  );
}

const command = process.argv[2];

if (command === "keygen") {
  if (existsSync(keyFile) && !process.argv.includes("--force")) {
    console.log(`A signing key already exists at ${keyFile}.\nReplacing it invalidates every activation code already issued (use --force only if you mean it).`);
    writePublicKey(publicKeyFor(loadSecret()));
    console.log("src/license/publicKey.ts refreshed from the existing key.");
    process.exit(0);
  }
  mkdirSync(keyDir, { recursive: true });
  const secretKey = randomBytes(32).toString("hex");
  writeFileSync(keyFile, JSON.stringify({ secretKey, createdAt: new Date().toISOString() }, null, 2), { mode: 0o600 });
  writePublicKey(publicKeyFor(secretKey));
  console.log(`Signing key created: ${keyFile}\nBACK THIS FILE UP somewhere safe and private. Then rebuild the app so it contains the new public key.`);
} else if (command === "issue") {
  const device = option("device");
  const name = option("name");
  if (!device || !name) throw new Error('Usage: issue --device ABCD-EFGH-JKLM --name "Shop name" [--days 365 | --expires YYYY-MM-DD]');
  if (!/^[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$/.test(normalizeDeviceCode(device))) {
    throw new Error(`"${device}" is not a device code. It looks like ABCD-EFGH-JKLM (12 letters/digits); put it in quotes if it has spaces.`);
  }
  const days = option("days");
  const expires = option("expires") ?? (days ? new Date(Date.now() + Number(days) * 86_400_000).toISOString().slice(0, 10) : null);
  if (expires && !/^\d{4}-\d{2}-\d{2}$/.test(expires)) throw new Error("--expires must look like 2027-12-31");
  const payload: LicensePayload = {
    v: 1,
    id: `LIC-${randomUUID().slice(0, 8).toUpperCase()}`,
    name: name.trim(),
    device: normalizeDeviceCode(device),
    issued: new Date().toISOString().slice(0, 10),
    expires
  };
  const code = issueLicense(loadSecret(), payload);
  mkdirSync(keyDir, { recursive: true });
  if (!existsSync(issuedLog)) appendFileSync(issuedLog, "licence id,shop,device,issued,expires\n");
  appendFileSync(issuedLog, `${payload.id},"${payload.name.replace(/"/g, '""')}",${payload.device},${payload.issued},${payload.expires ?? "never"}\n`);
  console.log(`Licence ${payload.id} for "${payload.name}" on device ${payload.device}${expires ? `, valid until ${expires}` : ", no expiry"}.\n\nSend this activation code to the shop (copy it exactly):\n\n${code}\n`);
} else if (command === "verify") {
  const device = option("device");
  const code = option("code");
  if (!device || !code) throw new Error("Usage: verify --device ABCD-EFGH-JKLM --code <activation code>");
  const result = verifyLicense(code, { publicKeyHex: publicKeyFor(loadSecret()), deviceCode: device });
  console.log(result.ok ? `Valid: ${JSON.stringify(result.license)}` : `Invalid (${result.reason}): ${result.message}`);
} else {
  console.log("Commands: keygen | issue --device <code> --name <shop> [--days N | --expires YYYY-MM-DD] | verify --device <code> --code <code>");
}
