/** Public half of the vendor's licence signing key (generated by `npm run license -- keygen`). */
export const LICENSE_PUBLIC_KEY = "afa4df424f237857aaf5a133bdde76fe65c940a14965ac0b40f9e7afcb8e8ac9";
